dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libx11-dev
      - libxrandr-dev
      - libudev-dev

install:
  pip install --user conan

script:
  - /usr/bin/g++-8 --version
  - mkdir build
  - cd build
  - export CXX=/usr/bin/g++-8
  - export CC=/usr/bin/gcc-8
  - echo $CXX
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - conan install .. --build missing
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE ..
  - cmake --build . -- -j2 
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-8



