language: cpp

matrix:
  include:
    - name: "gcc 7 Debug Coverage (ONLY_COVERAGE)"
      os: linux
      sudo: false
      env: COVERAGE=1 CXX_EXE=/usr/bin/g++-7 CC_EXE=/usr/bin/gcc-7 GCOV=/usr/bin/gcov-7 CMAKE_OPTS="-DONLY_COVERAGE:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libxrandr-dev
            - libudev-dev
            - g++-7
    - name: "clang 7 Debug (ONLY_COVERAGE libstdc++)"
      os: linux
      sudo: false
      env: CXX_EXE=/usr/bin/clang++-7 CC_EXE=/usr/bin/clang-7 GCOV=/usr/bin/gcov-8 CMAKE_OPTS="-DONLY_COVERAGE:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - libx11-dev
            - libxrandr-dev
            - libudev-dev
            - clang-7
            - clang-tools-7
            - libc++-7-dev 
            - libc++abi-7-dev
            - zlib1g-dev
    - name: "clang 7 Debug (libc++)"
      os: linux
      sudo: false
      env: CXX_EXE=/usr/bin/clang++-7 CC_EXE=/usr/bin/clang-7 GCOV=/usr/bin/gcov-8 CMAKE_OPTS="-DLIBCPP:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - libx11-dev
            - libxrandr-dev
            - libudev-dev
            - clang-7
            - clang-tools-7
            - libc++-7-dev 
            - libc++abi-7-dev
            - zlib1g-dev




install:
  pip install --user conan cmake

script:
  - $CXX_EXE --version
  - which cmake
  - cmake --version
  - export CXX=$CXX_EXE
  - export CC=$CC_EXE
  - echo $CXX
  - echo $CMAKE_OPTS
  - $CXX --version
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - cmake  $CMAKE_OPTS ..
  - VERBOSE=1 cmake --build . -- -j2
  - ctest -j2
  - if [ "${COVERAGE}" = "1" ]; then bash <(curl -s https://codecov.io/bash) -x $GCOV 2>/dev/null ; fi



