language: cpp

matrix:
  include:
    - name: "gcc 7 Debug Coverage"
      os: linux
      sudo: false
      env: COVERAGE=1 CXX_EXE=/usr/bin/g++-7 CC_EXE=/usr/bin/gcc-7 GCOV=/usr/bin/gcov-7 CMAKE_OPTS="-DONLY_COVERAGE:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libxrandr-dev
            - libudev-dev
            - g++-7

install:
  pip install --user conan

script:
  - export CXX=$CXX_EXE
  - export CC=$CC_EXE
  - echo $CXX
  - echo $CMAKE_OPTS
  - $CXX --version
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - conan install .. --build missing
  - cmake  $CMAKE_OPTS ..
  - VERBOSE=1 cmake --build . -- -j2
  - ctest -j2
  - if [ "${COVERAGE}" = "1" ]; then bash <(curl -s https://codecov.io/bash) -x $GCOV 2>/dev/null ; fi



